version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: time-deposit-db
    environment:
      POSTGRES_DB: timedeposit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - time-deposit-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d timedeposit" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-deposit-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/timedeposit
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - time-deposit-network

volumes:
  postgres_data:

networks:
  time-deposit-network:
    driver: bridge